# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
  - stage: stageA
    jobs:
      - job: A
        displayName: StageA-JobA
        pool:
          vmImage: windows-2019
        steps:
          - task: PowerShell@2
            inputs:
              targetType: inline
              script: |
               Write-Host $HOME

  - stage: stageB
    dependsOn: stageA
    jobs:
      - job: B
        displayName: StageB-JobB
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: uname -i
