# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: System Basic Info Checks!


variables:
- name: date
  value: Get-Date
- name: osinfo
  value: (Get-WMIObject win32_operatingsystem).name
trigger:
- master

stages:
- stage: StagefromA
  jobs:
  - job: LinuxfromstageA
    pool:
      vmImage: ubuntu-latest
      steps:
      - script: echo "Hello, world! from stageA"
      displayName: 'Onleine script in stage A linux machine'
  - job: WindowsfromstageA
    displayName: Windows-Pool-from-stageA
    pool:
     vmImage: 'windows-2019'
    steps:
     - script: |
        Write-Host "Hello All from StageA"
        Write-Host $(osinfo)
        Write-Host $(date)

- stage: StagefromB
  jobs:
  - job: LinuxfromstageB
    pool:
      vmImage: ubuntu-latest
      steps:
      - script: echo "Hello, world! from stageB"
        displayName: 'StageB-Linux'
  - job: WindowsfromstageB
    displayName: Windows-Pool-from-stageB
    pool:
     vmImage: 'windows-2019'
    steps:
     - script: |
        Write-Host "Hello All! from stageB"
        Write-Host $(osinfo)
        Write-Host $(date)