# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: spacegame-web
     trigger:
      branches:
        include:
          - main
          - Tailspin.SpaceGame.Web/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build Code from Repo
    jobs:
      - job: Restore
        steps:
          - task: NuGetCommand@2
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'

          - task: NuGetCommand@2
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              versioningScheme: 'off'
            
          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: 'b8b177ff-70f3-4250-970b-e0188e459df7'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'